# GitHub Pages Configuration
title: The Air Between Us
description: Illness and Inequality in a Connected World - A Century Course in Global Health at Duke University
url: https://airbetween.us
baseurl: ""

# Build settings
theme: null
plugins: []

# Exclude files from build
exclude:
  - README.md
  - LICENSE
  - CLAUDE.md
  - .claude/